### ISSUE TITLE
Add Alpine Lake Resort

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#18]
Alpine Lake Resort
700 W Alpine Dr, Terra Alta, WV 26764
46 Miles
Group code "Geo25"

https://www.myhms4.com/myres/bh/search.do?hotelCode=21166&Group=Geo25

(If anyone books this hotel, they are dumb, but they are offering a code, so who knows.)

**Comment by kkudlak45** [comment]
my dumbass forgot the code sorry
