### ISSUE TITLE
Rental Car sub-copy

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#2]
Let's make the copy under Rental Cars fit on one line by changing "The following companies are available at most major airports local to the area:" to "The following companies are available at most major airports in the area:"

**Comment by kkudlak45** [comment]
wouldn't focus too much on getting things on one line. the site is responsive and line breaks will change with screen resolution

![image](https://github.com/kkudlak45/gwxxi/assets/46248021/cc788407-1f67-4fb8-aae3-d95081cff752)
