### ISSUE TITLE
Alphabetize Sponsors

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#24]
The BDB and FoW need to be in ABC order, either horizontally or vertically.

**Comment by kkudlak45** [comment]
sorting is now case insensitive, sorry bout that

<img width="1509" alt="Screenshot 2024-07-28 at 10 31 55 PM" src="https://github.com/user-attachments/assets/61c381d6-39f6-48df-b3af-2af2a7369314">
