### ISSUE TITLE
Add https://www.visitmountaineercountry.com/Planner/ link

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#25]
As part of the Mon. CVB grant, we have to include this link somewhere on the website. https://www.visitmountaineercountry.com/Planner/

Let's add a yellow button to the Morgantown page under the two paragraphs at the top of the page. The button should say "CLICK HERE TO PLAN YOUR VISIT"

**Comment by kkudlak45** [comment]
![image](https://github.com/user-attachments/assets/e2f7c97a-2fbd-4f4c-a293-1123e01b0b2b)

**Comment by kkudlak45** [comment]
<img width="1530" alt="Screenshot 2024-07-28 at 10 27 49 PM" src="https://github.com/user-attachments/assets/18439bca-62d7-49cc-a9ca-477bfa96a098">
<img width="1523" alt="Screenshot 2024-07-28 at 10 28 01 PM" src="https://github.com/user-attachments/assets/3d60ffa9-522b-4b73-9c87-7e7c3f98603c">
<img width="1531" alt="Screenshot 2024-07-28 at 10 28 13 PM" src="https://github.com/user-attachments/assets/bc7e89ec-790b-4ea3-b9fc-c6c674f4e598">
