### ISSUE TITLE
Add MCTAF to platinum sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#26]
Please add the following image and link to both the home page and sponsor page under the Platinum sponsor banner. If you need a different size, let me know. https://www.visitmountaineercountry.com/grants/#Grant-Guidelines 

![MCTAF Sponsorship](https://github.com/user-attachments/assets/efae7f32-79ff-486a-914a-ab6bb525300c)

**Comment by kkudlak45** [comment]
<img width="663" alt="Screenshot 2024-07-28 at 10 22 03 PM" src="https://github.com/user-attachments/assets/be7442a1-0521-4388-b92a-acc96e76ada1">

**Comment by kkudlak45** [comment]
![image](https://github.com/user-attachments/assets/c0e01b1f-9e35-4f49-a8e3-f4e6c5b9870c)
