### ISSUE TITLE
Add Clarksburg Hilton Garden Inn

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#27]
Clarksburg Hilton Garden Inn
606 Emily Dr, Clarksburg, WV 26301
40 Miles

https://www.hilton.com/en/book/reservation/rooms/?ctyhocn=CKBGIGI&arrivalDate=2025-05-21&departureDate=2025-05-25&groupCode=GEO25&room1NumAdults=1&cid=OM%2CWW%2CHILTONLINK%2CEN%2CDirectLink

![Hilton Garden Inn](https://github.com/user-attachments/assets/723cf8de-bec7-4a8f-9718-7444c79a0f3a)

**Comment by kkudlak45** [comment]
<img width="1519" alt="Screenshot 2024-07-28 at 10 12 53 PM" src="https://github.com/user-attachments/assets/18d94d13-cecf-4cee-9a60-ac93c09d745f">
