### ISSUE TITLE
ADD DAYS INN HOTEL

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#29]
Days Inn - Fairmont
166 Middletown Rd, Fairmont, WV 26554
25 miles
https://www.wyndhamhotels.com/days-inn/fairmont-west-virginia/days-inn-fairmont/overview?CID=LC:iqv0j1dklijly45:12149&iata=00093796

<img width="996" alt="Screenshot 2024-08-14 at 2 29 21 PM" src="https://github.com/user-attachments/assets/48ec2f09-8baa-4b39-a878-355ed5e3a46d">

**Comment by kkudlak45** [comment]
![image](https://github.com/user-attachments/assets/4e638e6a-bd01-456f-a682-d207f06870da)
