### ISSUE TITLE
ADD HAMPTON INN HOTEL

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#30]
Hampton Inn - Fairmont
2121 Pleasant Valley Rd, Fairmont, WV 26554
24 Miles
https://www.hilton.com/en/attend-my-event/geocachewoodstock2025/

<img width="508" alt="Screenshot 2024-08-14 at 2 32 03 PM" src="https://github.com/user-attachments/assets/7f7de271-b451-427a-a071-9d2d82a94cf3">

**Comment by kkudlak45** [comment]
![image](https://github.com/user-attachments/assets/0ffd61f8-298f-4eab-84a8-5b60a8d680cf)
