### ISSUE TITLE
Update Black Diamond Backers and Friends of GeoWoodstock

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#31]
https://geowoodstockxxi.com/sponsors
https://docs.google.com/spreadsheets/d/1OfmnFb7c7aMAb-nWyCGkTFH468SUfq6i_NY_8YuRaj4/edit?gid=1508639641#gid=1508639641

**Comment by kkudlak45** [comment]
please stop opening issues for this. I do it every time I push an update
