### ISSUE TITLE
Update event page

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#32]
Please make sure all the event icons, names, dates, times, and descriptions match what is listed on this site. It's pretty much a complete overhaul of this page. You can also link the GC codes, although they won't go live until January.

https://markwebb.notion.site/Side-Events-aa5d6468596a490bbbc9852d877830dd

**Comment by kkudlak45** [comment]
<img width="1446" alt="Screenshot 2024-09-03 at 11 36 51 AM" src="https://github.com/user-attachments/assets/b094ae73-b348-4cfa-984b-152621e6e283">
<img width="1473" alt="Screenshot 2024-09-03 at 11 37 02 AM" src="https://github.com/user-attachments/assets/2a3ec03f-11f5-4316-9bac-a1d4889fabf6">
