### ISSUE TITLE
Change Columbus to "Akron-Canton"

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#34]

**Comment by GeoWoodstockXXI** [comment]
https://geowoodstockxxi.com/events

**Comment by GeoWoodstockXXI** [comment]
Under cache tours

**Comment by kkudlak45** [comment]
<img width="438" alt="Screenshot 2024-09-03 at 11 21 23 AM" src="https://github.com/user-attachments/assets/f1fe17ab-8a89-487d-ba2c-92f02538adf3">
