### ISSUE TITLE
Update FAQs - How far away are WVTim's caches

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#35]
https://geowoodstockxxi.com/faqs

"[WVTim's famous geocaches](https://www.geocaching.com/play/geotours/berkeley-gadgets) in the eastern panhandle are about 2.5 hours east of Morgantown. Many of these geocaches are challenging to complete and could take several days to finish the entire GeoTour, assuming all caches are operational. If you're interested in finding gadget caches but don't want to make the drive to Berkley County, a brand new gadget GeoTour will be available closer to GeoWoodstock XXI in nearby Marion County."

**Comment by kkudlak45** [comment]
<img width="1251" alt="Screenshot 2024-09-03 at 12 02 37 PM" src="https://github.com/user-attachments/assets/608a6a3f-523f-4022-a859-49de72d0554d">
