### ISSUE TITLE
NEW PAGE - Wild and Wonderful 21 Side Events

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#37]
I want a page under the "Info" tab that talks about what the Wild and Wonderful event series is, why people should attend, and a list of where and when they all are. We can talk more about this after they all publish.

**Comment by kkudlak45** [comment]
ok. taking this as no action needed now

**Comment by kkudlak45** [comment]
sept 15 has passed

**Comment by kkudlak45** [comment]
no action to be taken. bookmark list on geocaching.com is being used
