### ISSUE TITLE
[EVENTS] Change COPE course.

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#40]
Under the Almost Heaven Adventures event, change COPE to C.O.P.E. and add (Challenging Outdoor Personal Experiences). So it should read:

A trip to West Virginia isn’t complete without a little adventure. Visit Camp Mountaineer, a scouting reserve complete with a zip-line and C.O.P.E. (Challenging Outdoor Personal Experiences) course! Spend the morning hiking, caching, and testing your skills on the ropes. A group will also be heading to Fairmont to complete the F.L.O.A.T. series.

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 10 49 22 AM](https://github.com/user-attachments/assets/12e5c886-49cb-4212-8866-b09c377df94e)
