### ISSUE TITLE
[EVENTS] Add Friday non-event

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#41]
On the events & activities page, we need to add an event line to let people know that GeoWoodstock HQ will be open on Friday as well.

GeoWoodstock XXI
Friday (05/23)
10:00 A.M. - 3:00 P.M.

Come get a first look at GeoWoodstock XXI, pick up your registration packet, and shop the vendors. Doors open at 8 a.m. for VIPs and Friends of GeoWoodstock, with general admission starting at 10 a.m. This is a great chance to participate in some of the activities without all the crowds.

https://cdn.discordapp.com/attachments/1125228302030880778/1256071825285316669/EVENT_PARKING.png?ex=66dc614b&is=66db0fcb&hm=b6e26651bdf267c0ef4901a3c0c7ef761df9b4fb46c586e545f9c99cc1274126&

**Comment by kkudlak45** [comment]
Whatever icon you attached is gone, so I took a guess

![Screenshot 2024-09-20 at 10 53 15 AM](https://github.com/user-attachments/assets/2c0cf9ea-bd0d-46a5-8e25-c596e2765d67)
