### ISSUE TITLE
[HOTELS] Add Days Inn & Suites - Bridgeport

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#42]
Days Inn & Suites - Bridgeport
112 Tolley Dr, Bridgeport, WV 26330
Distance: 38 miles

[www.wyndhamhotels.com/hotels/04686?checkInDate=05/22/2025&checkOutDate=05/25/2025&groupCode=052225GEO](http://www.wyndhamhotels.com/hotels/04686?checkInDate=05/22/2025&checkOutDate=05/25/2025&groupCode=052225GEO)

<img width="898" alt="Days Inn" src="https://github.com/user-attachments/assets/4480ea94-67f2-465b-aec8-d58d8dc74791">

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 10 56 21 AM](https://github.com/user-attachments/assets/5bb8c65e-443b-4845-bd37-20a95c754636)
