### ISSUE TITLE
[HOTELS] Add Hampton Inn Morgantown

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#43]
Hampton Inn Morgantown
1053 Van Voorhis Road, Morgantown, WV 26505
Distance: 5 Miles

https://www.hilton.com/en/book/reservation/deeplink/?ctyhocn=MGWVVHX&groupCode=CHHGEO&arrivaldate=2025-05-22&departuredate=2025-05-25&cid=OM,WW,HILTONLINK,EN,DirectLink&fromId=HILTONLINKDIRECT

<img width="424" alt="Hampton Inn" src="https://github.com/user-attachments/assets/6decf403-448d-4824-b98b-e6b0aa4ee99b">

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 10 57 47 AM](https://github.com/user-attachments/assets/a4faf923-d364-4519-bc46-57c3bb2dda00)

fysa there are now 2 hamptons in morgantown
