### ISSUE TITLE
[SPONSORS] Edited Mountaineer Country CVB link

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#44]
I have permission from the Visit Mountaineer Country CVB to change the link from the grants page to their homepage. Clicking on the "VISIT MOUNTAINEER COUNTRY.COM" button should take people to https://www.visitmountaineercountry.com/

**Comment by GeoWoodstockXXI** [comment]
![VMC Transparent](https://github.com/user-attachments/assets/803adb0f-b6c7-4b4b-94fc-0e710ebc42a6)

Adding transparent png 1:1

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 10 58 49 AM](https://github.com/user-attachments/assets/e36373df-1bdf-4074-9a7e-10436883d0c4)

there was an issue already opened for this which I already resolved. Did you want a transparent bg or something?

**Comment by kkudlak45** [comment]
per text convo

![Screenshot 2024-09-20 at 11 03 14 AM](https://github.com/user-attachments/assets/2b2f7071-cdb1-4e5b-9973-df69181dabed)
