### ISSUE TITLE
[SPONSORS] Add Blackwater Outdoor Adventures Silver Sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#45]
Add Blackwater Outdoor Adventures as a silver level sponsor

https://www.blackwateroutdooradventures.com
![BOA](https://github.com/user-attachments/assets/284d2421-d8d3-4c18-bc13-8051ac66c03d)

**Comment by GeoWoodstockXXI** [comment]
![BOAT](https://github.com/user-attachments/assets/29e9be39-2d59-49bd-9b37-ffe9288859f1)

Here is a version with a white background. Which works better?

**Comment by kkudlak45** [comment]
transparent background, png file, 1x1 ratio

**Comment by kkudlak45** [comment]
on second thought, white in this case (sorry)

**Comment by kkudlak45** [comment]
use transparent when you want the website background color to take precedence, use filled when you want your image background to take precedence

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 11 01 05 AM](https://github.com/user-attachments/assets/eb58778e-3346-478b-ad3d-50fb6a8f695c)

**Comment by kkudlak45** [comment]
feel like that maybe looks weird. using white bg instead
![Screenshot 2024-09-20 at 11 01 53 AM](https://github.com/user-attachments/assets/b6c38245-7215-44ea-9410-bc40cf295c0a)

**Comment by kkudlak45** [comment]
used transparent versions of logos

![Screenshot 2024-09-20 at 11 05 26 AM](https://github.com/user-attachments/assets/92ba8c94-96fa-4ef3-81dd-3c5762a18cb4)
