### ISSUE TITLE
[HOTELS] Add Fairfield Inn & Suites Marriott - Fairmont

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#46]
Fairfield Inn & Suites Marriott - Fairmont
27 Southland Dr, Fairmont, WV 26554
25 Miles
https://www.marriott.com/event-reservations/reservation-link.mi?id=1725645270833&key=GRP&guestreslink2=true

<img width="518" alt="Screenshot 2024-09-07 at 2 00 52 PM" src="https://github.com/user-attachments/assets/044ea227-ec2a-4c75-9b3e-e83376d7d7b5">

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 11 13 23 AM](https://github.com/user-attachments/assets/b2e440a2-77bb-423c-88e2-4e23a51f734b)
