### ISSUE TITLE
[EVENTS] Change times to all EST

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#47]
Times should be set so you can type the times in with plain text to reflect EST local time.

**Comment by kkudlak45** [comment]
Switched my timezone to London and times are the same (this was mostly an internal change so it's hard to show)

![Screenshot 2024-09-20 at 11 22 48 AM](https://github.com/user-attachments/assets/877e95f2-7a93-4cb4-b60d-34eba8eae5c3)
