### ISSUE TITLE
[EVENTS] Breakfast With The Mommas

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#48]
Change "Meet the Mommas" to "Breakfast With The Mommas"

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 11 24 21 AM](https://github.com/user-attachments/assets/d40e7fda-884d-41b2-905d-7d60e632a214)

hey journalism major - I'm pretty sure prepositions and articles don't get capitalized in titles 🙄🙄🙄🙄
