### ISSUE TITLE
[SPONSOR] Pathtags.com

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#49]
![Pathtag_bumpersticker](https://github.com/user-attachments/assets/a9e0d08e-592a-4a82-a095-77df2af081cf)
https://www.pathtags.com

I need you to add Pathtags to a platinum sponsor on both the home page and the sponsors page.

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 11 26 50 AM](https://github.com/user-attachments/assets/ee631471-e8d6-4a9c-8ee2-46b4e79f870b)
![Screenshot 2024-09-20 at 11 27 08 AM](https://github.com/user-attachments/assets/78adaa17-fdf2-4915-84e4-0e5a4c51ff47)
