### ISSUE TITLE
[EVENTS] Change day of week for GWXXI

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#50]
On the first GeoWoodstock XXI event listing, the day says Tuesday (5/23). It should read Friday (5/23).

<img width="255" alt="Screenshot 2024-09-26 at 1 31 29 PM" src="https://github.com/user-attachments/assets/d8e91048-1d39-4a9a-9cc4-7b1c0e46188d">

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 02 11 PM](https://github.com/user-attachments/assets/71ff4b9e-c511-4b13-a2fc-e52822880d79)
