### ISSUE TITLE
[SPONSORS] Add "Heart of Civil War GeoTrail" to bronze sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#51]
Add "Heart of Civil War GeoTrail" to bronze sponsor. Link it to https://www.heartofthecivilwar.org

![HCWHA Logo 2023 - RGB](https://github.com/user-attachments/assets/081bd9a7-7db6-44f0-aa61-c385f08a9023)

**Comment by GeoWoodstockXXI** [comment]
Inb4 you ask for a square version:

![3](https://github.com/user-attachments/assets/927b35f2-6e4d-4e49-8127-1bacaa33a0d7)

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 06 23 PM](https://github.com/user-attachments/assets/c013df95-60cc-4f9d-9ef5-281364
![Screenshot 2024-10-11 at 4 06 39 PM](https://github.com/user-attachments/assets/79bc34f0-9a8a-4eeb-9c05-0f7ba4a463f8)
582f60)

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 07 01 PM](https://github.com/user-attachments/assets/291f4af9-6187-43ba-b9c1-a5d318677b52)
