### ISSUE TITLE
[SPONSORS] Add Martinsburg CVB to Platinum sponsor page.

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#52]

**Comment by GeoWoodstockXXI** [comment]
![MartinsburgBerkeleyCoLOGO-CVB-color](https://github.com/user-attachments/assets/9c0530eb-50e5-47ac-8130-2fd7130e4eb7)


Add this logo to the Platinum level sponsors page with the link TravelWV.com

**Comment by GeoWoodstockXXI** [comment]
![2](https://github.com/user-attachments/assets/bf880bc2-d2d8-4c7b-b465-fe7a99c83c70)

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 08 19 PM](https://github.com/user-attachments/assets/f787ff61-4723-4687-9722-fda46665e63e)
