### ISSUE TITLE
[HOME] Add Martinsburg CVB as a platinum sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#53]
Add this logo to the Platinum level sponsors section with the link TravelWV.com

![MartinsburgBerkeleyCoLOGO-CVB-color](https://github.com/user-attachments/assets/4f639f79-0a4e-483c-af30-d602a9b8b37a)

**Comment by GeoWoodstockXXI** [comment]
In b4 you ask for a square version:

![2](https://github.com/user-attachments/assets/1cb277ad-7bd0-4eb4-b4e3-a0514601936c)

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 13 31 PM](https://github.com/user-attachments/assets/e92743aa-21db-4899-bf23-417bc34b8ab0)
