### ISSUE TITLE
[SPONSORS] Add Marion CVB as platinum sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#54]
Add Marion CVB as platinum sponsor

MarionCVB.com

![marion_logo_withslogan-01 (2)](https://github.com/user-attachments/assets/c9bc0731-8663-425b-8ea8-002545e7e916)

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 09 51 PM](https://github.com/user-attachments/assets/acd97eed-3961-4af1-a419-3654e1867636)
