### ISSUE TITLE
[HOME] Add Marion CVB as platinum sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#55]
Add Marion CVB as platinum sponsor
MarionCVB.com

![marion_logo_withslogan-01 (2)](https://github.com/user-attachments/assets/5e63dc3d-3697-4ee8-9c3e-53497d7d7e01)

**Comment by kkudlak45** [comment]
![Screenshot 2024-10-11 at 4 13 49 PM](https://github.com/user-attachments/assets/99cfd28f-fbe3-43fa-a6d5-ab73dfe7380d)
