### ISSUE TITLE
[SPONSOR] Add Team Maltese as a silver level sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#57]
![Team Maltese Logo](https://github.com/user-attachments/assets/7d24dfa3-0f66-4fb5-92fa-ec92a171e6c4)

Link here: https://www.geocaching.com/p/?guid=2227f7b2-ff37-4847-a1a3-743405f02419&wid=1345141b-666e-4f6b-80ea-b5b36146f51d&ds=2

**Comment by kkudlak45** [comment]
<img width="1509" alt="Screenshot 2024-10-25 at 8 12 11 PM" src="https://github.com/user-attachments/assets/dfbe91ef-d03c-4c5f-b58d-58f3530e5364">
