### ISSUE TITLE
[TRAVEL] Update Hampton Inn Image

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#58]
The Hampton Inn at 1053 Van Voorhis Road, Morgantown, WV should have the following image:

![1053 Van Voorhis Road, Morgantown, WV ](https://github.com/user-attachments/assets/72d01ca3-54e1-44eb-ac24-bd3f412bab0b)

**Comment by kkudlak45** [comment]
<img width="1533" alt="Screenshot 2024-10-25 at 8 13 42 PM" src="https://github.com/user-attachments/assets/471b6e17-4f0a-4f27-9747-f194ef32ad1a">
