### ISSUE TITLE
[REGISTER] Fix Questions typo

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#59]
At the bottom of the register page, FREQUENTLY ASKED QUETIONS should read, FREQUENTLY ASKED QUESTIONS.

**Comment by kkudlak45** [comment]
<img width="1545" alt="Screenshot 2024-10-25 at 8 14 22 PM" src="https://github.com/user-attachments/assets/d03046ad-5c46-42bd-8e2a-d1da3c8fc4fd">
