### ISSUE TITLE
[HOME] Update the "Shop" banner text

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#60]
Just above the sponsors section on the home page, please change the text next to the shop icon to the following:

Registration for GeoWoodstock XXI is now open, and with packages ranging from free to VIP, there is something for everyone. Check out the trackables, shirts, pathtags, and more available for pre-order until January 31, 2025. All individuals are encouraged to attend, and with á la carte options, you can make the right package for you! Thanks for supporting GeoWoodstock XXI!

**Comment by kkudlak45** [comment]
<img width="1559" alt="Screenshot 2024-11-14 at 9 44 27 AM" src="https://github.com/user-attachments/assets/1c699c51-9f73-441d-af99-600b8ccdea45">
