### ISSUE TITLE
[HOME] Update "Shop Now" link

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#61]
On the home page just above the sponsors section, let's change the "SHOP NOW" link to lead to www.GeoWoodstockXXI.com/Register.

Let's make clicking the license plate image also link to www.GeoWoodstockXXI.com/Register.

**Comment by kkudlak45** [comment]
<img width="1232" alt="Screenshot 2024-11-14 at 9 49 08 AM" src="https://github.com/user-attachments/assets/f9d56837-66ca-4146-8f2f-f9ff1191a333">
<img width="495" alt="Screenshot 2024-11-14 at 9 49 25 AM" src="https://github.com/user-attachments/assets/7fdc0cf5-836c-43f8-86b4-cdad4a531396">
