### ISSUE TITLE
[Events & Activities} Update Country Roads Challenge Description

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#62]
Please change the description for the Country Roads Challenge event to:

Welcome to Wild and Wonderful West Virginia - nowhere is this statement more true than Coopers Rock State Park. Join us for a casual meet and greet while you pick up your Country Roads Challenge playing card and enjoy the breathtaking views of the Cheat River. At 10 a.m., new caches placed at local businesses throughout Morgantown will be released. Find all 10 and earn a limited edition “Country Roads Challenge” Geocoin. No purchase is necessary to attend but to be guaranteed a limited-edition coin, you’ll need to purchase a SWAG package.

**Comment by kkudlak45** [comment]
<img width="1551" alt="Screenshot 2024-11-14 at 9 51 17 AM" src="https://github.com/user-attachments/assets/33cef223-4e58-44e3-b499-a7b80bd6957e">
