### ISSUE TITLE
[TRAVEL & LODGING] Add United flights to Morgantown.

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#63]
Directly under the line that says "Morgantown Municipal Airport (MGW) 9 miles", add the following:

🚨 **Update**: United Airlines now offers direct flights from IAD and ORD to MGW.

You can shrink the text size to ensure it fits on one line.

**Comment by kkudlak45** [comment]
<img width="1555" alt="Screenshot 2024-11-14 at 9 59 13 AM" src="https://github.com/user-attachments/assets/cf5e70c6-df63-46aa-ad1d-50fe9dce1caa">
<img width="358" alt="Screenshot 2024-11-14 at 9 59 44 AM" src="https://github.com/user-attachments/assets/d92859c8-58ea-476a-993b-4fc10cac98bb">

I don't love the way this looks

**Comment by kkudlak45** [comment]
<img width="1240" alt="Screenshot 2024-11-14 at 10 04 57 AM" src="https://github.com/user-attachments/assets/c9bd545a-5eba-4f09-833f-624e9bf72cc8">
<img width="374" alt="Screenshot 2024-11-14 at 10 06 17 AM" src="https://github.com/user-attachments/assets/7ec7101c-cf6a-4254-8e8d-a9dab05132a0">

im gonna do it this way and u can cry to me if u want it changed
