### ISSUE TITLE
[TRAVEL & LODGING] Add "Camp Mountaineer"

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#64]
Under campgrounds, add the following:

Camp Mountaineer
187 Camp Mountaineer Rd, Morgantown, WV 26508
Distance: 16 miles
Call 304-366-3940 and mention GeoWoodstock

![Camp Mountaineer](https://github.com/user-attachments/assets/2c1983e2-1cdb-4ad4-b8a5-9f5122f4e4ba)

**Comment by kkudlak45** [comment]
<img width="1624" alt="Screenshot 2024-11-14 at 10 13 00 AM" src="https://github.com/user-attachments/assets/6247000e-6374-4550-97fc-ac99027d128f">
