### ISSUE TITLE
[TRAVEL & LODGING] Mylan Park KOA campground

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#65]
After you add Camp Mountaineer, I want the four campgrounds currently listed to be displayed in a 2x2 grid with the "CLICK HERE FOR A FULL LIST OF CAMPGROUNDS" button under them. Directly under that, I want you to add a gray box similar to the shop banner from the home page. The Mylan Park KOA image (the one that says coming soon) should appear on the left with the bold text of "Mylan Park KOA" above this new block of text (get rid of the text currently listed):

A new KOA campground is under construction at Mylan Park and is scheduled to be completed in time for GeoWoodstock XXI. At this time, no RV reservations for the parking area are being made. Reservations for the new KOA will be available in March 2025. Please mark your intention to attend and join our mailing list to be notified when bookings are available.

Hyperlink "mark your intention to attend" to https://www.geocaching.com/live/geocache/GCANXX1/log

Add a gold button with the text: SIGN UP FOR OUR MAILING LIST and link to https://geowoodstockxxi.us17.list-manage.com/subscribe?u=8fcc636b5362e252a516c4a10&id=68d2e501c0

**Comment by kkudlak45** [comment]
<img width="1576" alt="Screenshot 2024-11-14 at 11 08 36 AM" src="https://github.com/user-attachments/assets/4c53a577-9ab1-4885-aaec-7aaef067de6e">

<img width="1661" alt="Screenshot 2024-11-14 at 11 08 50 AM" src="https://github.com/user-attachments/assets/c7764860-1910-43f1-ba86-f9a4bff7909e">

<img width="1782" alt="Screenshot 2024-11-14 at 11 09 11 AM" src="https://github.com/user-attachments/assets/3f400268-da4f-401c-aee9-b84bbb1caaf7">

<img width="1683" alt="Screenshot 2024-11-14 at 11 09 24 AM" src="https://github.com/user-attachments/assets/c0b1625f-cec3-4cab-ac17-04b8cf10becc">

<img width="426" alt="Screenshot 2024-11-14 at 11 09 45 AM" src="https://github.com/user-attachments/assets/8915ea2e-eebb-42a8-ab78-09da4c5f109b">
