### ISSUE TITLE
[SPONSORS] Add Mylan Park as a silver level sponsor

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#66]
SILVER LEVEL SPONSOR. https://mylanpark.org

![Mylan Park sponsorship](https://github.com/user-attachments/assets/22235acf-312e-44c1-9ced-1c42a78bdc8e)

**Comment by kkudlak45** [comment]
<img width="1790" alt="Screenshot 2024-11-14 at 10 17 23 AM" src="https://github.com/user-attachments/assets/84742c7f-3301-4bdf-8ddf-b4ce175c81a0">
