### ISSUE TITLE
[SPONSORS] Reduce spacing in sections

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#67]
Under the "Silver" and "Bronze" level sponsorship rows (like, below the logos), there appears to be an extra space or two.

**Comment by kkudlak45** [comment]
no there isnt

it just looks like that bc of the transparency on the images

<img width="1790" alt="Screenshot 2024-11-14 at 10 18 45 AM" src="https://github.com/user-attachments/assets/c9626180-4acf-4f43-b050-02ca42f835ae">

<img width="1771" alt="Screenshot 2024-11-14 at 10 23 10 AM" src="https://github.com/user-attachments/assets/8f49f8ea-9945-4d9a-a357-cb114c923778">

<img width="1779" alt="Screenshot 2024-11-14 at 10 23 33 AM" src="https://github.com/user-attachments/assets/7db9c160-0139-4bda-9e74-788eb1faf99a">

<img width="1773" alt="Screenshot 2024-11-14 at 10 23 19 AM" src="https://github.com/user-attachments/assets/0208e84d-8d5e-45cd-9954-f5b4a9a24b90">

**Comment by kkudlak45** [comment]
leaving open so u can read and suggest alternative if something needs changed

**Comment by kkudlak45** [comment]
shit i accidentally closed

**Comment by kkudlak45** [comment]
i wonder if maybe the perceived space is from the absence of the little dot icons

**Comment by GeoWoodstockXXI** [comment]
Ok - if there isn't a space there then it's all good. Hopefully we can fill these sponsor sections completely up lol
