### ISSUE TITLE
[REGISTER] Add the following FAQ

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#68]
**Can VIPs bring guests into preferred areas?**
Yes – those attending in the same party will have the opportunity to travel together to preferred lines and VIP-only areas.

**How does the Country Roads Challenge work?**
10 caches will be published around Mountaineer Country starting at 10 a.m. on Thursday (5/22/25). Passports will be available in all paid registration levels and available on Thursday at the Country Roads Challenge kickoff event or during package pickup at Mylan Park. Participants will have all weekend to find all 10 caches to claim a limited-edition trackable coin, courtesy of Visit Mountaineer Country. After Sunday, coins can be claimed on a first-come, first-served basis at the visitor center. For more information, please visit the event page for the Country Roads Challenge Kickoff (GCANXX0).

**How do I get my Friends of GeoWoodstock coin?** 
By becoming a Friend of GeoWoodstock XXI, you’ll receive a beautiful golden coin, minted only for our highest supporters. This coin will be available with your registration package when you pick up your SWAG. If you have already purchased a Friends of GeoWoodstock supporter package, but are unable to attend the event, please email info@GeoWoodstockXXI.com for assistance.

**When will we get to see the bonus coin included in the VIP package?**
You’ll see what this coin truly looks like when you pick up your package in May, but trust us, this is a special coin design you’ll want to add to your collection.

**Can I register at the free level and upgrade later?**
We are encouraging all attendees to register through the online store, even if this is at the free level. If you know you are likely to purchase a SWAG package, there is no need to register at the free level and upgrade later, simply make one purchasing decision when you are ready.

**What’s for lunch?**
Lunch will be held at Mylan Park on Saturday (5/24/25) from 11 a.m. to 2 p.m. The primary lunch option will be pepperoni rolls and WV hotdogs, staples for the area. Gluten-free options are similar, with the hot dog buns and pasta being gluten-free. Vegetarian options include a black bean burger as well as a fruit cup.

**Comment by kkudlak45** [comment]
<img width="1212" alt="Screenshot 2024-11-14 at 10 30 59 AM" src="https://github.com/user-attachments/assets/64e4ef96-d90c-4b6a-8be8-b9fbe0d70d79">
