### ISSUE TITLE
[REGISTER] Add "update" section

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#70]
Below the title, but above the first paragraph, please add a red call-out section that looks similar to the updates section of coord.info/GCANXX1. (So red text box with rounded edges)

In larger white bold text, put the following: The last day to purchase your Black Diamond Backer shirt is November 29, 2024. This pre-event fundraiser is the only item available for shipping and makes an excellent holiday gift for that special cacher. Inventory is limited, so don't delay snagging yours because once they're gone, they're gone!

**Comment by kkudlak45** [comment]
I'll do you one better: obnoxious alert on every page that links to the shop
<img width="411" alt="Screenshot 2024-11-14 at 10 41 31 AM" src="https://github.com/user-attachments/assets/81cf3548-a9f7-44c2-941b-75b84cf978c6">
<img width="1781" alt="Screenshot 2024-11-14 at 10 41 45 AM" src="https://github.com/user-attachments/assets/e73b210c-e6b3-4bd6-8cff-bbea4c5bdd13">
