### ISSUE TITLE
[SPONSORS] Add Bronze Sponsor - GeocacheTalk

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#73]
http://geocachetalk.com/

![GeocacheTalk](https://github.com/user-attachments/assets/f94a2c40-d589-4203-8e24-571a0c0258b0)

**Comment by kkudlak45** [comment]
![Screenshot 2024-12-01 at 10 37 15 PM](https://github.com/user-attachments/assets/90a8fd4d-cbd2-4896-8259-961951573a44)
