### ISSUE TITLE
[TRAVEL] Reorder campgrounds

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#74]
Please reorder campgrounds by distance to Mylan Park. So Camp Mountaineer would be first on the list.

**Comment by kkudlak45** [comment]
![Screenshot 2024-12-01 at 10 35 27 PM](https://github.com/user-attachments/assets/ec9c12e3-2991-4808-a7e7-fc4b8c5dc9d6)

sorry i assumed it already did this and did not pay attention
