### ISSUE TITLE
[HOTELS] Add "Sonesta Essential - Morgantown"

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#76]
Sonesta Essential - Morgantown
15 Lawless Rd, Morgantown, WV 26501
5 miles
https://www.sonesta.com/sonesta-essential/wv/morgantown/sonesta-essential-morgantown?isGroupCode=true&groupCode=GEO&checkin=2025-05-23&checkout=2025-05-25

![18](https://github.com/user-attachments/assets/06505f00-ad87-460c-a205-f73195106c49)

**Comment by kkudlak45** [comment]
![Screenshot 2024-12-01 at 10 32 31 PM](https://github.com/user-attachments/assets/bb852104-5ecf-4d52-b30d-982890bd619d)
