### ISSUE TITLE
[HOTELS] Add "Sonesta Essential - Fairmont"

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#77]
Sonesta Essential - Fairmont
20 Southland Dr, Fairmont, WV 26554
25 Miles
https://www.sonesta.com/sonesta-essential/wv/fairmont/sonesta-essential-fairmont?isGroupCode=true&groupCode=GEO&checkin=2025-05-23&checkout=2025-05-25

![19](https://github.com/user-attachments/assets/4c127dc3-6dfe-42ab-9e42-a33c721987d0)

**Comment by kkudlak45** [comment]
![Screenshot 2024-12-01 at 10 26 57 PM](https://github.com/user-attachments/assets/2291ed3c-dafb-462e-9378-3e314510a655)
