### ISSUE TITLE
[SITE WIDE] Add info bar at the top

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#83]
Similar to the code you did for the closing of the black diamond baker sale, please add a new bar with the following text:

Registration for GeoWoodstock XXI will close on January 31, 2025. Please consider helping support the event by registering and buying coins, SWAG, and other items. Click here to register [www.GeoWoodstockXXI.com/Register].

**Comment by kkudlak45** [comment]
<img width="1790" alt="Screenshot 2024-12-29 at 3 47 55 PM" src="https://github.com/user-attachments/assets/a63b469e-925d-4946-908c-cc76e3ee9bfe" />
