### ISSUE TITLE
[EVENTS] Change CITO the line text

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#84]
Change CITO the line text to:

Marking the boundary between West Virginia and Pennsylvania, join us at the westernmost point that Charles Mason and Jeremiah Dixon personally surveyed. These trailblazers embraced the true meaning of Mountaineer spirit, and we’re going to embody that attitude with some trail maintenance and environmental reclamation efforts around the park.

**Comment by kkudlak45** [comment]
<img width="1539" alt="Screenshot 2024-12-29 at 3 49 12 PM" src="https://github.com/user-attachments/assets/106ac78c-a737-49c7-907c-34e2932d3679" />
