### ISSUE TITLE
[EVENTS] Add GPS adventures maze

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#85]
Add 2 line items on the calendar for the same date and times as the GeoWoodstock XXI events.

Header:  GPS Adventures Maze Exhibit

Friday (05/23)
10:00 AM - 03:00 PM

One of the rarest icons in all of Geocaching is making an appearance at GeoWoodstock XXI! This is a must-see during your time at the event. VIPs and Friends of GeoWoodstock can tour the exhibit starting at 8 a.m. with general admission starting at 10 a.m. This is a great chance to participate in some of the activities without all the crowds.

Header:  GPS Adventures Maze Exhibit

Saturday (05/24)
08:00 AM - 05:00 PM

One of the rarest and most sought-after icons in the game, the GPS Adventures Maze Exhibit, will make an exciting appearance at GeoWoodstock XXI in Morgantown, WV! This unique, interactive exhibit offers geocachers of all levels the chance to explore the history, tools, and techniques of this global adventure, while also earning the coveted icon by completing the maze and signing the log.

![GPS Maze](https://github.com/user-attachments/assets/a6dc2160-48d9-42d8-9491-ce6781e09be2)

**Comment by kkudlak45** [comment]
<img width="1651" alt="Screenshot 2024-12-29 at 3 59 26 PM" src="https://github.com/user-attachments/assets/4296ac75-f68d-461d-bfdc-733378e0978c" />
