### ISSUE TITLE
[EVENTS] Hyperlink Event Titles

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#86]
Country Roads Challenge : coord.info/GCANXX0
CITO The Line : coord.info/GCANXX2
Mountain Music : coord.info/GCANXX3
Almost Heaven Adventures : coord.info/GCANXX5
GeoWoodstock XXI : coord.info/GCANXX1
GPS Adventures Maze Exhibit : coord.info/GCANAAA
Woodstock On The Wharf : coord.info/GCATNZJ
GeoWoodstock XXI : coord.info/GCANXX1
GPS Adventures Maze Exhibit : coord.info/GCANAAA
Midnight Madness : coord.info/GCANXX6
Breakfast With The Mommas : coord.info/GCANXX7
Farewell From The Fort : coord.info/GCANXX8

**Comment by kkudlak45** [comment]
<img width="1791" alt="Screenshot 2024-12-29 at 4 09 34 PM" src="https://github.com/user-attachments/assets/e0f8ed17-bb21-48b4-95fa-629f0f105f9b" />
