### ISSUE TITLE
[FAQ] About The Weekend -> How many days should I plan to attend?

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#87]
Updated "With 8 events..." to "With 10 events..."

**Comment by kkudlak45** [comment]
<img width="1547" alt="Screenshot 2024-12-29 at 4 10 58 PM" src="https://github.com/user-attachments/assets/d06e8d38-e4b9-4a2f-b6a8-de96d2e541a2" />
