### ISSUE TITLE
Replace Quality Inn photo

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#9]
The picture you have listed for the Quality Inn and suites is the Comfort Inn. All your info is correct we just need to swap out the picture. 

![EVENT PARKING](https://github.com/kkudlak45/gwxxi/assets/174143699/0a952e45-5d9d-447e-b23d-a43b4bfa7cde)

**Comment by GeoWoodstockXXI** [comment]
![EVENT PARKING](https://github.com/kkudlak45/gwxxi/assets/174143699/8372792c-d0a0-4293-86aa-ff3459d45203)

**Comment by GeoWoodstockXXI** [comment]
Use the photo without the white boarder lol

**Comment by kkudlak45** [comment]
> Use the photo without the white boarder lol

damnit mark i already used the one with the border
